
sonar.projectKey=anthracite-labs_AppT
sonar.organization=anthracite-labs
sonar.projectName=AppT

sonar.sources=app/src/main,samsung/src/main,backend/src
sonar.tests=app/src/test,backend/test

sonar.java.binaries=app/build/intermediates/javac/debug/classes,app/build/tmp/kotlin-classes/debug

sonar.coverage.jacoco.xmlReportPaths=build/reports/kover/report.xml,app/build/reports/kover/report.xml,app/build/reports/kover/reportDebug.xml,build/reports/kover/reportDebug.xml
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.qualitygate.wait=true
