config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: true
    ignoreDataClasses: true

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreEnums: true
    ignoreConstantDeclaration: true
  WildcardImport:
    active: true
  ReturnCount:
    active: true
    max: 3
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: ['Preview']
  MaxLineLength:
    active: true
    maxLineLength: 120

potential-bugs:
  active: true
  LateinitUsage:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
